Crediyi/Crediyi/Controllers/ClientesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Crediyi.Models;

namespace Crediyi.Controllers
{
    public class ClientesController : Controller
    {

        CrediYiEntities Context = new CrediYiEntities();

        // GET: Clientes
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult ListarClientes()
        {
            try
            {
                List<Clientes> Lclientes = (from cc in Context.Clientes
                                            select cc).ToList();

                if (Lclientes.Count >= 1)
                {
                    return View(Lclientes.ToList());
                }
                else 
                    throw new Exception("No hay Clientes para mostrar");
                
            }
            catch (Exception )
            {

                ViewBag.Mesaje = "Error: No se pudieron listar los datos de clientes."; //ex.Message;
                return View(new List<CompraCabezal>());
            }
        }


        [HttpGet]
        public ActionResult ReporteDeCompras(int? NumDoc)
        {
            try
            {
                List<CompraCabezal> CompraxCli = (from compra in Context.CompraCabezal
                                                  where compra.Clientes.NumDoc == NumDoc.Value
                                                  orderby compra.Fecha 
                                                  select compra).ToList();

                if (CompraxCli.Count >= 1)
                {
                    return View(CompraxCli.ToList());
                }

                else
                {
                    ViewBag.Mesaje = "No hay Compras para dicha CI";
                    return View(new List<CompraCabezal>());
                }
            }
            catch (Exception )
            {

                ViewBag.Mesaje = "Error: No se pudo listar los Datos para dicha CI."; //ex.Message;
                return View(new List<CompraCabezal>());
            }

        }



        [HttpGet]
        public ActionResult DetalleLineas(string Serie, int Numero)
        {
            try
            {
                List<LineaCabezal> Dlineas = (from linea in Context.LineaCabezal
                                              where linea.Serie == Serie && linea.Numero == Numero
                                              select linea).ToList();

                if (Dlineas.Count >= 1)
                {
                    return View(Dlineas.ToList());
                }

                else
                {
                    ViewBag.Mesaje = "No hay Lineas para dicha Compra";
                    return View(new List<LineaCabezal>());
                }
                   
            }
            catch (Exception )
            {
                ViewBag.Mesaje = "Error: No se pudo obtener los Datos Detallados."; // ex.Message;
                return View(new List<LineaCabezal>());
            }
        }


        [HttpGet]
        public ActionResult ReporteDeComprasGenerico()
        {
            try
            {
                List<CompraCabezal> Compra = (from compra in Context.CompraCabezal
                                              orderby compra.Fecha
                                              select compra).ToList();

                if (Compra.Count >= 1)
                {
                    return View(Compra.ToList());
                }

                else
                {
                    ViewBag.Mesaje = "No hay Compras para visualizar.";
                    return View(new List<CompraCabezal>());
                }
            }
            catch (Exception)
            {

                ViewBag.Mesaje = "Error: No se pudo listar los Datos."; //ex.Message;
                return View(new List<CompraCabezal>());
            }

        }


        [HttpGet]
        public ActionResult DetalleLineasTotal(string Serie, int Numero)
        {
            try
            {
                List<LineaCabezal> Dlineas = (from linea in Context.LineaCabezal
                                              where linea.Serie == Serie && linea.Numero == Numero
                                              select linea).ToList();

                if (Dlineas.Count >= 1)
                {
                    return View(Dlineas.ToList());
                }

                else
                {
                    ViewBag.Mesaje = "No hay Lineas para dicha Compra";
                    return View(new List<LineaCabezal>());
                }

            }
            catch (Exception)
            {
                ViewBag.Mesaje = "Error: No se pudo obtener los Datos Detallados."; // ex.Message;
                return View(new List<LineaCabezal>());
            }
        }



    }
}

Crediyi/Crediyi/Controllers/CompraCabezalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

/////////////////////////
using Crediyi.Models;
/////////////////////////


namespace Crediyi.Controllers
{
    public class CompraCabezalController : Controller
    {
        CrediYiEntities Context = new CrediYiEntities();

        // GET: CompraCabezal
        public ActionResult Index()
        {
            return View();
        }


        [HttpGet]
        public ActionResult AltaCompraCabezal()
        {
            try
            {
                ViewBag.ListaClientes = new SelectList(Context.Clientes.ToList(), "IdCliente", "Nombre");

                return View();
            }
            catch (Exception )
            {
                List<Clientes> _Lista = new List<Clientes>();
                ViewBag.Mensaje = "No se pudo cargar el Formulario."; //ex.Message;
                ViewBag.ListaClientes = new SelectList(Context.Clientes.ToList(), "IdCliente", "Nombre");
                return View();
            }
        }


        [HttpPost]
        public ActionResult AltaCompraCabezal(CompraCabezal CC) 
        {
            try
            {
                CC.Clientes = Context.Clientes.Where(c => c.IdCliente == CC.IdCliente).FirstOrDefault();

                if (CC.Clientes == null)
                    {  throw new Exception("El Cliente especificado no existe");  }
                else
                {
                    CC.Fecha = DateTime.Now;

                    Session["CC"] = CC;

                    //Valido el modelo
                    CC.Validar();

                    Context.CompraCabezal.Add(CC);

                    Context.SaveChanges();

                    ViewBag.ListaClientes = new SelectList(Context.Clientes.ToList(), "IdCliente", "Nombre");
                    return RedirectToAction("AltaLineaCabezal", "LineaCabezal");
                
                }

            }
            catch (Exception ex)
            {
                ViewBag.Mensaje = ex.Message; // "No se pudo dar de alta el Cabezal de Compra."; //ex.Message;
                Context.Entry(CC).State = System.Data.Entity.EntityState.Detached;
                ViewBag.ListaClientes = new SelectList(Context.Clientes.ToList(), "IdCliente", "Nombre");
                return View();
            }
        }



 


    }
}

Crediyi/Crediyi/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Crediyi.Models;

namespace Crediyi.Controllers
{
    public class HomeController : Controller
    {
        CrediYiEntities Context = new CrediYiEntities();

        // GET: Home
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult MenuPrincipal()
        {
            return View();
        }


        [HttpGet] 
        public ActionResult Logueo()
        { return View(); }


        [HttpPost] 
        public ActionResult Logueo(Usuarios U)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    U = Context.Usuarios.Where(usu => usu.Usu == U.Usu && usu.Pass == U.Pass).FirstOrDefault();
                    return RedirectToAction("MenuPrincipal", "Home");
                }
                else
                    return View();
            
            }
            catch (Exception )
            {
                ViewBag.Mesaje = "Error al intentar Loguearse."; // ex.Message;
                return View();
            }
        }


    }
}

Crediyi/Crediyi/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

</BR>
</BR>

<div>
    @Html.ActionLink("Logueo", "Logueo")
</div>

Crediyi/Crediyi/Views/Home/Logueo.cshtml
@model Crediyi.Models.Usuarios

@{
    ViewBag.Title = "Logueo";
}

<h2>Logueo</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Ingrese los datos para loguearse</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Usu, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Usu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Usu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Pass, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PasswordFor(model => model.Pass, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Pass, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="LogIn" class="btn btn-default" />
            </div>
        </div>
    </div>

    <div>
        <br />
        @ViewBag.Mensaje
    </div>
}

<div>
    @Html.ActionLink("Inicio", "Index")
</div>

Crediyi/Crediyi/Views/Home/MenuPrincipal.cshtml
@{
    ViewBag.Title = "MenuPrincipal";
}

<h2>Menú Principal</h2>


@Html.ActionLink("Crear Compra", "AltaCompraCabezal", "CompraCabezal", new { area = "" }, new { @class = "navbar-brand" })
<br />

<hr />
@Html.ActionLink("Reporte de Compras por Cliente", "ListarClientes", "Clientes", new { area = "" }, new { @class = "navbar-brand" })
<br />

<hr />
@Html.ActionLink("Reporte de Compras", "ReporteDeComprasGenerico", "Clientes", new { area = "" }, new { @class = "navbar-brand" })
<br />